### ISSUE TITLE
Time: 0 under Golang 1.4.1 ?

### ISSUE THREAD

**Issue by RKelln** [amir/raidman#7]
I think I'm seeing some odd behaviour when I use Golang 1.4.1: the Time when Riemann receives it is 0:
(Using #(info %)):
```
#riemann.codec.Event{:host my.host.com, :service myservice, :state , :description , :metric 0.004504022, :tags [mytag], :time 0, :ttl 0.0}
```

If I use 1.3.3 then the time looks like:
```:time 1.423863708783E9```

Setting the Time explicitly in the event also doesn't seem to help. 

Anyone else see this or is my go install broken?

**Comment by amir** [comment]
There's indeed a change of behaviour in `go1.4`:

```go
package main

import (
	"fmt"
	"reflect"
)

func main() {
	var Ttl float32
	var Time int64
	intZeroValue := reflect.Zero(reflect.ValueOf(Time).Type())
	floatZeroValue := reflect.Zero(reflect.ValueOf(Ttl).Type())

	fmt.Printf("%t\n%t\n", intZeroValue == reflect.ValueOf(Time), floatZeroValue == reflect.ValueOf(Ttl))
}
```

`go1.3` prints:
```
true
true
```
but `go1.4` prints:
```
false
false
```

Will investigate. Thanks for reporting.

**Comment by amir** [comment]
I just pushed a fix for this change of behaviour in go1.4. Could you please confirm whether this fixes the issue?

**Comment by RKelln** [comment]
This looks like it is working locally, still need to test on the server. Thanks very much, will let you know when it is fully tested.

**Comment by RKelln** [comment]
Working under 1.4.2 as well, tested locally and on server. As long as that doesn't cause regressions on previous versions, this looks good to me. Thanks!

**Comment by amir** [comment]
Thank you. I added a test case, and also tested it against 1.3.
